---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: nodejs-build
spec:
  workspaces:
    - name: shared
  params:
    - name: GIT_REPO
      type: string
      default: "https://github.com/sparlampe/DO288-apps"
    - name: GIT_REVISION
      type: string
      default: "OCP4.12"
    - name: APP_PATH
      type: string
      default: "apps/pipelines-creation/exchange"
    - name: IMAGE
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/exchange:latest"

  tasks:
   - name: fetch-repository
     taskRef:
       resolver: git
       params:
         - name: url
           value: https://github.com/tektoncd/catalog.git
         - name: revision
           value: main
         - name: pathInRepo
           value: task/git-clone/0.9/git-clone.yaml
     params:
      - name: url
        value: $(params.GIT_REPO)
      - name: revision
        value: $(params.GIT_REVISION)
      - name: subdirectory
        value: ""
      - name: deleteExisting
        value: "true"
      - name: sslVerify
        value: "false"
     workspaces:
       - name: output
         workspace: shared
   - name: build-image
     taskRef:
       resolver: git
       params:
         - name: url
           value: https://github.com/tektoncd/catalog.git
         - name: revision
           value: main
         - name: pathInRepo
           value: task/buildah/0.9/buildah.yaml
     params:
       - name: IMAGE
         value: $(params.IMAGE)
       - name: DOCKERFILE
         value: Containerfile
       - name: CONTEXT
         value: $(params.APP_PATH)
       - name: TLSVERIFY
         value: "false"
       - name: SKIP_PUSH
         value: "false"
     runAfter:
        - fetch-repository
     workspaces:
        - name: source
          workspace: shared      