postgres:
  user: ""
  pass: ""
  db: "sampledb"

expenseService:
  replicaCount: 1
  image: "quay.io/redhattraining/ocpdev-expense-service:4.12"
  host: "expense-service"
  domain: "apps-crc.testing"
